dockerfiles/scripts/install_cran_pkgs.R
Additional packages for optimizing GH action workflows.
=> Additional CRAN packages

.github/workflows/deploy.yaml, dockerfiles/Dockerfile_r-ver_4.1.0_bioc_3.13, dockerfiles/Dockerfile_rstudio_4.1.0_bioc_3.13, dockerfiles/Dockerfile_tidyverse_4.1.0_bioc_3.13, dockerfiles/Dockerfile_verse_4.1.0_bioc_3.13
Add buildx caching to docker build.
=> Add cache@main

dockerfiles/Dockerfile_rstudio_4.1.0_bioc_3.13, dockerfiles/scripts/install_cran_pkgs.R
Addresses https://github.com/insightsengineering/ci-images/issues/1
=> Copy phantomjs to global PATH

dockerfiles/scripts/install_cran_pkgs.R
related to: https://github.com/insightsengineering/ci-images/issues/1
=> copy phantom

.github/workflows/deploy.yaml
=> typo in conf 

dockerfiles/scripts/install_cran_pkgs.R
Add the pillar and rtables packages.
=> Add pillar and rtables

.gitlab-ci.yml
=> Fix pipeline

dockerfiles/scripts/install_cran_pkgs.R
Adds the oysteR R package for vulnerability management.
=> Add the oysteR R package

.gitlab-ci.yml
Update gitlab-ci pipeline with longer job timeout.
=> Add gitlab-ci timeout and new tags

.gitlab-ci.yml, dockerfiles/scripts/install_sysdeps.sh
=> gitlab settings

dockerfiles/scripts/install_sysdeps.sh
to solve a conflict with system dependencies
=> fix  libs conflict

dockerfiles/scripts/install_cran_pkgs.R
This will be used for rendering markdowns from within RStudio.
=> Install the markdown package

dockerfiles/scripts/install_cran_pkgs.R
Install tinytex for PDF builds.
=> Install tinytex for TeX PDF builds

dockerfiles/scripts/install_cran_pkgs.R
Add the missing `makeindex` package.
=> Add makeindex package

.github/workflows/deploy.yaml, .github/workflows/scheduled_build.yaml
Closes: insightsengineering/automation-tasks#170
Add scheduled triggered build for predefined images. Test run: https://github.com/insightsengineering/ci-images-test/actions
=> Scheduled builds

.github/workflows/scheduled_build.yaml
=> Fix branch bug

dockerfiles/scripts/install_cran_pkgs.R, dockerfiles/scripts/install_gh_pkgs.R, dockerfiles/scripts/install_sysdeps.sh
For better CI runtime performance.
=> Add jags and a GH package

dockerfiles/scripts/install_gh_pkgs.R
The one on CRAN has a few issues.
Closes https://github.com/insightsengineering/ci-images/issues/36
=> Add styler from Github to rstudio-local

.github/CODEOWNERS, dockerfiles/scripts/install_gh_pkgs.R
=> Add ggnewscale

dockerfiles/scripts/install_cran_pkgs.R
=> matrix version is still not working, try install from source first

dockerfiles/scripts/install_cran_pkgs.R
=> adding must reinstall package list, recompile tmb from source

Dockerfile, scripts/install_pip_pkgs.py, scripts/install_sysdeps.sh
=> Support pip packages, refactor a bit

scripts/install_cran_pkgs.R
=> adding package, close #54

scripts/install_other_pkgs.R
=> installing cmdstanr

scripts/install_sysdeps.sh
Add system dependency required for `RPostgres`.
=> Add system dependency required for `RPostgres`

scripts/install_cran_pkgs.R, scripts/install_sysdeps.sh
=> install libreoffice-common and rpackage doconv
